package com.fablecities.android.worldgen

// GENERATED by tools/probe_sprites.mjs from the REAL effects/sprites.js + VehicleSpray.js.
// Do not edit. Sprites.kt must reproduce these exactly.
object SprayGoldens {
    const val SPRAY_CHECKSUM = 3193836.0
    val SPRAY_ALPHA = doubleArrayOf(0.0, 0.0, 0.0, 0.0, 2.0, 40.0, 0.0, 0.0, 1.0, 39.0, 0.0, 0.0, 0.0)
    const val RING_CHECKSUM = 3567908.0
    val RING_ALPHA = doubleArrayOf(0.0, 0.0, 6.0, 0.0, 10.0, 75.0, 0.0)
    const val FLAKE_CHECKSUM = 850756.0
    val FLAKE_ALPHA = doubleArrayOf(0.0, 0.0, 157.0, 3.0, 30.0, 0.0)
    const val STREAK_CHECKSUM = 6646490.0
    val STREAK_ALPHA = doubleArrayOf(0.0, 0.0, 0.0, 8.0, 221.0, 0.0)
    val SEED_BLOCK = doubleArrayOf(0.050462570041418076, -0.7185860276222229, 0.656933605670929, 0.056210000067949295, 0.7970929741859436, 0.8299328088760376, 0.6883100271224976, 0.3233128488063812, -0.9073039889335632, 0.6816616058349609, 0.4283599853515625, 0.09549999982118607, 0.06703628599643707, 0.5163300037384033)
    val SPRAY_IDX = intArrayOf(0, 1, 63, 64, 403, 1000, 2047, 123, 456, 789, 2048, 3003, 4095)
    val RING_IDX = intArrayOf(0, 40, 100, 1023, 2049, 3000, 4095)
    val FLAKE_IDX = intArrayOf(0, 31, 300, 511, 700, 1023)
    val STREAK_IDX = intArrayOf(0, 100, 2050, 4100, 6000, 8191)
    val SEED_IDX = intArrayOf(0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 27, 28, 139)
}
