// GENERATED by tools/probe_star.mjs — golden values from the REAL web environment/StarField.js
// (buildStarCubeTexture + buildMoonTexture, seed 1337). Do not edit by hand.
package com.fablecities.android.worldgen

object StarGoldens {
    const val face0Sum = 47474171
    const val face1Sum = 46717734
    const val face2Sum = 49020016
    const val face3Sum = 48906190
    const val face4Sum = 50334805
    const val face5Sum = 48456823
    const val moonSum = 76132566
    val texelProbes = listOf(
        listOf(0, 28, 255, 249, 254, 95),
        listOf(0, 16400, 255, 248, 251, 104),
        listOf(0, 32772, 255, 247, 248, 69),
        listOf(0, 49144, 236, 236, 255, 2),
        listOf(1, 432, 236, 236, 255, 0),
        listOf(1, 16804, 236, 236, 255, 0),
        listOf(1, 33176, 236, 236, 255, 0),
        listOf(1, 49548, 236, 236, 255, 0),
        listOf(2, 836, 236, 236, 255, 10),
        listOf(2, 17208, 236, 236, 255, 12),
        listOf(2, 33580, 236, 236, 255, 13),
        listOf(2, 49952, 236, 236, 255, 18),
        listOf(3, 1240, 241, 239, 255, 12),
        listOf(3, 17612, 240, 239, 255, 12),
        listOf(3, 33984, 239, 238, 255, 13),
        listOf(3, 50356, 238, 237, 255, 14),
        listOf(4, 1644, 255, 248, 252, 4),
        listOf(4, 18016, 255, 247, 248, 4),
        listOf(4, 34388, 255, 246, 244, 5),
        listOf(4, 50760, 255, 245, 239, 6),
        listOf(5, 2048, 236, 236, 255, 5),
        listOf(5, 18420, 236, 236, 255, 5),
        listOf(5, 34792, 236, 236, 255, 6),
        listOf(5, 51164, 236, 236, 255, 7),
    )
    val moonProbes = listOf(
        listOf(28, 79, 255),
        listOf(16400, 62, 255),
        listOf(32772, 13, 255),
        listOf(49144, 13, 255),
        listOf(65516, 115, 255),
        listOf(81888, 135, 255),
        listOf(98260, 168, 255),
        listOf(114632, 193, 255),
        listOf(131004, 114, 255),
        listOf(147376, 153, 255),
        listOf(163748, 152, 255),
        listOf(180120, 157, 255),
    )
}
