// GENERATED by tools/probe_water.mjs — golden values from the REAL web water stack
// (Heightmap.js computeShoreDistance + textures.js makeNoiseTexture / makeWaterNormalTexture
// + Water.js _buildGeometry quad scan + THREE.DataUtils.toHalfFloat, size 2048 spacing 4 seed
// 1337 — the native grid). Do not edit by hand.
package com.fablecities.android.worldgen

object WaterGoldens {
    val shoreProbes = listOf(255, 255, 255, 118, 255, 0, 255, 255, 0, 255, 0, 255, 255, 255, 0)
    val shoreCells = listOf(listOf(0, 0), listOf(129, 300), listOf(257, 257), listOf(300, 129), listOf(400, 500), listOf(500, 400), listOf(129, 129), listOf(300, 300), listOf(456, 123), listOf(88, 512), listOf(512, 512), listOf(356, 256), listOf(420, 420), listOf(45, 456), listOf(500, 128))
    const val shoreUnder = 57020
    val noiseProbes = listOf(
        listOf(127, 72, 160, 185),
        listOf(182, 99, 130, 52),
        listOf(170, 95, 74, 81),
        listOf(150, 77, 102, 97),
        listOf(125, 87, 152, 91),
        listOf(122, 73, 93, 95),
        listOf(146, 82, 98, 84),
        listOf(172, 122, 140, 40),
        listOf(189, 107, 109, 63),
        listOf(166, 128, 93, 15),
        listOf(137, 115, 98, 165),
        listOf(106, 80, 102, 68),
        listOf(108, 119, 140, 120),
        listOf(93, 139, 177, 62),
        listOf(120, 87, 113, 85),
        listOf(124, 117, 149, 181),
    )
    val wnormalProbes = listOf(
        listOf(116, 55, 232, 255),
        listOf(66, 163, 233, 255),
        listOf(148, 149, 251, 255),
        listOf(38, 81, 206, 255),
        listOf(149, 45, 222, 255),
        listOf(178, 204, 215, 255),
        listOf(176, 91, 239, 255),
        listOf(100, 156, 248, 255),
        listOf(112, 90, 248, 255),
        listOf(125, 136, 254, 255),
        listOf(138, 157, 250, 255),
        listOf(132, 104, 252, 255),
        listOf(131, 197, 233, 255),
        listOf(176, 123, 245, 255),
        listOf(194, 100, 232, 255),
        listOf(69, 111, 240, 255),
    )
    const val noiseByteSum = 30768118
    const val wnormalByteSum = 48884915
    val halfProbes = listOf(52768, 51232, 47104, 43622, 0, 10854, 15872, 18112, 19968, 22018, 22880, 23810, 24576, 24954)
    val quadProbes = listOf(-384.0, -1024.0, -256.0, -896.0, -256.0, -1024.0, -128.0, -896.0, -384.0, -896.0, -256.0, -768.0, -256.0, -896.0, -128.0, -768.0, -384.0, -768.0, -256.0, -640.0, -256.0, -768.0, -128.0, -640.0, -384.0, -640.0, -256.0, -512.0, -256.0, -640.0, -128.0, -512.0, -384.0, -512.0, -256.0, -384.0, -256.0, -512.0, -128.0, -384.0, -384.0, -384.0, -256.0, -256.0, -512.0, -256.0, -384.0, -128.0)
    const val quadCount = 87
}
