// GENERATED by tools/probe_wetlights.mjs — goldens from the REAL web WetLights.js update()
// (synthetic camera + lamp mesh + traffic-lamp-glare mesh, exposure 1.0, planeY 0)
package com.fablecities.android.worldgen

object WetLightsGoldens {
    const val published = 6
    const val statsLamps = 5
    const val statsVehicles = 3
    const val tailsInSlots = 2
    /** 12 slots: x, y, z, intensity, r, g, b */
    val slots = listOf(
        listOf(-4.0, 0.62, -46.0, 1.98, 1.0, 0.8939393939393938, 0.712121212121212),
        listOf(4.0, 0.62, -44.0, 1.98, 1.0, 0.8939393939393938, 0.712121212121212),
        listOf(-30.0, 9.0, -44.0, 3.2, 1.0, 0.8, 0.58),
        listOf(2.0, 0.66, -26.0, 2.6, 1.0, 0.075, 0.03),
        listOf(16.0, 0.66, -28.0, 1.56, 1.0, 0.075, 0.03),
        listOf(30.0, 9.0, -40.0, 3.2, 1.0, 0.8, 0.58),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
        listOf(0.0, -10000.0, 0.0, 0.0, 1.0, 1.0, 1.0),
    )
}
