// Effect-sprite golden probe — runs the REAL effects/sprites.js makeSpray / makeRing /
// makeSnowflake / makeRainStreak in Node and emits SprayGoldens.kt (checksums + scattered
// texel values). The Kotlin port (worldgen/Sprites.kt) must reproduce these exactly.
import { writeFileSync } from 'node:fs';
import { makeSpray, makeRing, makeSnowflake, makeRainStreak } from '../src/modules/effects/sprites.js';
import { VehicleSpray } from '../src/modules/effects/VehicleSpray.js';

const K = (v) => {
  const s = String(v);
  return /^-?\d+$/.test(s) ? `${s}.0` : s;
};

function checksum(data) {
  // bytes as unsigned, summed with float64 accumulation (JS += semantics)
  let sum = 0;
  for (let i = 0; i < data.length; i++) sum += data[i];
  return sum;
}
function samples(data, stride, idxs) {
  return idxs.map((i) => { const v = data[i * stride + 3]; if (v === undefined) throw new Error('idx out of range ' + i); return v; });
}

const spray = makeSpray(1337).image.data;
const ring = makeRing(64).image.data;
const flake = makeSnowflake(32).image.data;
const streak = makeRainStreak(32, 256).image.data;

// the VehicleSpray constructor's per-slot seed block (44 emitters × 36 — probe a 5×7 slice)
const vs = new VehicleSpray({ emitters: 5, perEmitter: 7, texture: {} });
const seedBlock = vs.geometry.getAttribute('aSeed').array;
const sampleF = (arr, idxs) => idxs.map((i) => { const v = arr[i]; if (v === undefined) throw new Error('idx out of range ' + i); return v; });

const SPRAY_IDX = [0, 1, 63, 64, 403, 1000, 2047, 123, 456, 789, 2048, 3003, 4095];
const RING_IDX = [0, 40, 100, 1023, 2049, 3000, 4095];
const FLAKE_IDX = [0, 31, 300, 511, 700, 1023];
const STREAK_IDX = [0, 100, 2050, 4100, 6000, 8191];
const SEED_IDX = [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 27, 28, 139];

const L = [];
L.push('package com.fablecities.android.worldgen');
L.push('');
L.push('// GENERATED by tools/probe_sprites.mjs from the REAL effects/sprites.js + VehicleSpray.js.');
L.push('// Do not edit. Sprites.kt must reproduce these exactly.');
L.push('object SprayGoldens {');
L.push(`    const val SPRAY_CHECKSUM = ${checksum(spray)}.0`);
L.push(`    val SPRAY_ALPHA = doubleArrayOf(${samples(spray, 4, SPRAY_IDX).map((v) => K(v)).join(', ')})`);
L.push(`    const val RING_CHECKSUM = ${checksum(ring)}.0`);
L.push(`    val RING_ALPHA = doubleArrayOf(${samples(ring, 4, RING_IDX).map((v) => K(v)).join(', ')})`);
L.push(`    const val FLAKE_CHECKSUM = ${checksum(flake)}.0`);
L.push(`    val FLAKE_ALPHA = doubleArrayOf(${samples(flake, 4, FLAKE_IDX).map((v) => K(v)).join(', ')})`);
L.push(`    const val STREAK_CHECKSUM = ${checksum(streak)}.0`);
L.push(`    val STREAK_ALPHA = doubleArrayOf(${samples(streak, 4, STREAK_IDX).map((v) => K(v)).join(', ')})`);
L.push(`    val SEED_BLOCK = doubleArrayOf(${sampleF(seedBlock, SEED_IDX).map((v) => K(v)).join(', ')})`);
L.push(`    val SPRAY_IDX = intArrayOf(${SPRAY_IDX.join(', ')})`);
L.push(`    val RING_IDX = intArrayOf(${RING_IDX.join(', ')})`);
L.push(`    val FLAKE_IDX = intArrayOf(${FLAKE_IDX.join(', ')})`);
L.push(`    val STREAK_IDX = intArrayOf(${STREAK_IDX.join(', ')})`);
L.push(`    val SEED_IDX = intArrayOf(${SEED_IDX.join(', ')})`);
L.push('}');
writeFileSync('android/app/src/test/java/com/fablecities/android/worldgen/SprayGoldens.kt', L.join('\n') + '\n');
console.log('SprayGoldens.kt written; spray checksum', checksum(spray));
