// Star field golden probe — runs the REAL web environment/StarField.js in Node and emits
// android/app/src/test/java/com/fablecities/android/worldgen/StarGoldens.kt
// Covers buildStarCubeTexture (Milky Way cube, seed 1337) and buildMoonTexture (512x256 albedo).
import { writeFileSync } from 'node:fs';
import { buildStarCubeTexture, buildMoonTexture, STAR_ALPHA_SCALE } from '../src/modules/environment/StarField.js';

const SEED = 1337;
const t0 = performance.now();
const cube = buildStarCubeTexture(SEED);
const moon = buildMoonTexture(SEED);
console.log('starfield ms', (performance.now() - t0).toFixed(1), 'alphaScale', STAR_ALPHA_SCALE);

const faces = cube.images.map((tex) => tex.image.data);
const sums = faces.map((f) => f.reduce((s, v) => s + (v < 0 ? v + 256 : v), 0));
const moonData = moon.image.data;
const moonSum = moonData.reduce((s, v) => s + (v < 0 ? v + 256 : v), 0);
console.log('face sums', sums.join(','), 'moonSum', moonSum);

// probe texels: spread through each face (face 0-5), and through the moon map
const probes = [];
for (let f = 0; f < 6; f++) {
  for (let i = 0; i < 4; i++) {
    const k = ((i * 4093 + 7 + f * 101) % (256 * 256)) * 4;
    probes.push([f, k, faces[f][k], faces[f][k + 1], faces[f][k + 2], faces[f][k + 3]]);
  }
}
const moonProbes = [];
for (let i = 0; i < 12; i++) {
  const k = ((i * 4093 + 7) % (512 * 256)) * 4;
  moonProbes.push([k, moonData[k], moonData[k + 3]]);
}

const kotlin = `// GENERATED by tools/probe_star.mjs — golden values from the REAL web environment/StarField.js
// (buildStarCubeTexture + buildMoonTexture, seed 1337). Do not edit by hand.
package com.fablecities.android.worldgen

object StarGoldens {
    const val face0Sum = ${sums[0]}
    const val face1Sum = ${sums[1]}
    const val face2Sum = ${sums[2]}
    const val face3Sum = ${sums[3]}
    const val face4Sum = ${sums[4]}
    const val face5Sum = ${sums[5]}
    const val moonSum = ${moonSum}
    val texelProbes = listOf(
${probes.map((p) => `        listOf(${p[0]}, ${p[1]}, ${p[2]}, ${p[3]}, ${p[4]}, ${p[5]})`).join(',\n')},
    )
    val moonProbes = listOf(
${moonProbes.map((p) => `        listOf(${p[0]}, ${p[1]}, ${p[2]})`).join(',\n')},
    )
}
`;
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/StarGoldens.kt', import.meta.url), kotlin);
console.log('StarGoldens.kt written');
