// Weather golden probe — runs the REAL web Weather.js (src/modules/environment/Weather.js)
// in Node and emits android/app/src/test/.../worldgen/WeatherGoldens.kt.
// The Kotlin port (worldgen/Weather.kt) must reproduce init / transitions / wetness /
// snow accumulation / wind wander bit-exactly.
//
// Weather.js imports THREE (Vector2) and SimplexNoise + math helpers — the three-shim
// node_modules used by the other probes provides both.
import { writeFileSync } from 'node:fs';
import { Weather, WEATHER_PRESETS } from '../src/modules/environment/Weather.js';

const SEED = 1337;

const J = (v) => {
  if (!Number.isFinite(v)) throw new Error('non-finite golden');
  return v;
};
function doubleHex(v) {
  const b = new DataView(new ArrayBuffer(8));
  b.setFloat64(0, v);
  let s = '';
  for (let i = 0; i < 8; i++) s += b.getUint8(i).toString(16).padStart(2, '0');
  return s.toUpperCase();
}
// JS prints the shortest round-trip decimal — Kotlin parses it back to the same double.
// Only integer-looking values need a '.0' so they stay Double literals inside doubleArrayOf.
const K = (v) => {
  if (!Number.isFinite(v)) throw new Error('non-finite golden: ' + v);
  const s = String(v);
  return /^-?\d+$/.test(s) ? `${s}.0` : s;
};

// web weather.state is a named-key object; project it into the Kotlin 16-slot row layout:
// [cover, type, cirrus, fog, fogH, fogFloor, turbidity, sun, diffuse, milk, skyFog, wind, rain, snow, temp, density]
const KEYS = ['cover', 'type', 'cirrus', 'fog', 'fogH', 'fogFloor', 'turbidity', 'sun', 'diffuse', 'milk', 'skyFog', 'wind', 'rain', 'snow', 'temp', 'density'];
const row = (w) => KEYS.map((k) => w.state[k]);
const tail = (w) => [w.state.precipitation, w.wetness, w.snowCover, w.wind.x, w.wind.y, w.windStrength];

const L = [];
L.push('package com.fablecities.android.worldgen');
L.push('');
L.push('/** Generated by tools/probe_weather.mjs from the REAL web Weather.js — do not edit. */');
L.push('object WeatherGoldens {');
L.push('    val SEED = ' + SEED);

// --- 1. init state of every preset (constructor) ---
L.push('    // init state after the constructor, per preset: [16 preset keys, precipitation, wetness, snowCover, windX, windZ, windStrength]')
const initProbes = {};
for (const name of Object.keys(WEATHER_PRESETS)) {
  const w = new Weather(SEED, name);
  initProbes[name] = w;
  L.push(`    val INIT_${name.toUpperCase()} = doubleArrayOf(`);
  L.push('        ' + [...row(w), ...tail(w)].map(K).join(', ') + ',');
  L.push('    )');
}

// --- 2. transition sequence: clear -> rain -> snow -> fog, 30 real-second steps ---
// the site drives weather.update(dt, gameSeconds) with gameSeconds = game-clock seconds;
// dt = real seconds between frames (0.5 = 30 fps stepping for the goldens)
const seqProbes = [];
{
  const w = new Weather(SEED, 'clear');
  const steps = [];
  let gameSeconds = 14.0 * 3600.0; // hour 14, the site default
  const emit = (tag) => {
    steps.push({ tag, vals: [...row(w), ...tail(w)], time: w.time });
  };
  emit('clear_t0');
  w.set('rain');
  for (let i = 0; i < 20; i++) { w.update(0.5, gameSeconds); gameSeconds += 15.0; if (i === 4 || i === 9 || i === 19) emit(`rain_t${i}`); }
  w.set('snow');
  for (let i = 0; i < 20; i++) { w.update(0.5, gameSeconds); gameSeconds += 15.0; if (i === 9 || i === 19) emit(`snow_t${i}`); }
  w.set('fog');
  for (let i = 0; i < 20; i++) { w.update(0.5, gameSeconds); gameSeconds += 15.0; if (i === 9 || i === 19) emit(`fog_t${i}`); }
  seqProbes.push({ seed: SEED, steps });
}
L.push('    // transition sequence rows: tag + full weather state')
L.push('    val SEQ_TAGS = arrayOf(');
for (const s of seqProbes[0].steps) L.push(`        "${s.tag}",`);
L.push('    )');
L.push('    val SEQ_ROWS = arrayOf(');
for (const s of seqProbes[0].steps) {
  L.push('        doubleArrayOf(' + [...s.vals, s.time].map(K).join(', ') + '),');
}
L.push('    )');

// --- 3. real-time path (gameSeconds = null): time accumulates by dt ---
{
  const w = new Weather(SEED, 'cloudy');
  for (let i = 0; i < 8; i++) w.update(0.25);
  L.push('    val REALTIME_CLOUDY_8 = doubleArrayOf(');
  L.push('        ' + [...row(w), ...tail(w), w.time].map(K).join(', ') + ',');
  L.push('    )');
}

// --- 4. drying: rain 30 s then back to clear for 3 minutes ---
{
  const w = new Weather(SEED, 'rain');
  w.update(0.5, 3600.0);
  w.set('clear');
  for (let i = 0; i < 360; i++) w.update(0.5, 3600.0 + i * 0.5);
  L.push('    val DRYING_AFTER_RAIN = doubleArrayOf(');
  L.push('        ' + [...row(w), ...tail(w)].map(K).join(', ') + ',');
  L.push('    )');
}

// --- 5. derived getters at a known moment (cloudCover / sunFactor / driftWind) ---
{
  const w = new Weather(SEED, 'cloudy');
  for (let i = 0; i < 12; i++) w.update(0.5, 43200.0 + i * 15.0);
  L.push(`    val DERIVED_CLOUDY = doubleArrayOf(${K(w.cloudCover)}, ${K(w.sunFactor)}, ${K(w.driftWind)}, ${K(w.state.turbidity)}, ${K(w.state.fog)}, ${K(w.state.milk)}, ${K(w.state.skyFog)}, ${K(w.state.precipitation)})`);
}

L.push('}');
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/WeatherGoldens.kt', import.meta.url), L.join('\n') + '\n');
console.log('WeatherGoldens.kt written:', L.length, 'lines');
