// Water golden probe — runs the REAL web water stack in Node and emits
// android/app/src/test/java/com/fablecities/android/worldgen/WaterGoldens.kt
//
// Covers:
//  1. Heightmap.js at the NATIVE grid resolution (size 2048, spacing 4, seed 1337) — the grid
//     already pinned bit-exact by WorldGenParityTest.
//  2. Heightmap.computeShoreDistance() — the exact EDT shoreline SDF (Uint8 payload 128 + 4·sd).
//  3. textures.js makeNoiseTexture(256, 1337) — tileable RGBA fBm.
//  4. textures.js makeWaterNormalTexture(256, 3) — 18-wave tangent normal map.
//  5. Water.js _buildGeometry quad scan (chunkSize 128) + toHalfFloat patterns.
import { readFileSync, writeFileSync } from 'node:fs';
import { Heightmap } from '../src/modules/terrain/Heightmap.js';
import { makeNoiseTexture, makeWaterNormalTexture } from '../src/modules/terrain/textures.js';
import { DataUtils } from 'three';

const hm = new Heightmap({ size: 2048, spacing: 4, seed: 1337 }).generate();
const N = hm.N;
let mnH = Infinity, mxH = -Infinity;
for (let i = 0; i < hm.data.length; i++) { const h = hm.data[i]; if (h < mnH) mnH = h; if (h > mxH) mxH = h; }
console.log('grid', N, 'min', mnH.toFixed(3), 'max', mxH.toFixed(3));

// ---- 2. shore distance --------------------------------------------------------------------
const t0 = performance.now();
const shore = hm.computeShoreDistance();
console.log('shore ms', (performance.now() - t0).toFixed(1));

// ---- 5. water quads (Water.js _buildGeometry scan, chunkSize 128, horizon ring half*3) -----
const t1 = performance.now();
const chunkSize = 128, wl = hm.waterLevel;
const count = Math.round(hm.size / chunkSize);
const quads = [];
for (let cz = 0; cz < count; cz++) for (let cx = 0; cx < count; cx++) {
  const x0 = -hm.half + cx * chunkSize, z0 = -hm.half + cz * chunkSize;
  const i0 = Math.round((x0 + hm.half) / hm.spacing), j0 = Math.round((z0 + hm.half) / hm.spacing);
  const n = Math.round(chunkSize / hm.spacing);
  let mn = Infinity;
  for (let j = j0; j <= j0 + n; j++) for (let i = i0; i <= i0 + n; i++) { const h = hm.data[j * N + i]; if (h < mn) mn = h; }
  if (mn < wl + 0.8) quads.push([x0, z0, x0 + chunkSize, z0 + chunkSize]);
}
// horizon ring: 4 big quads around the map (Water.js pushes these before meshing)
const H = hm.half, E = hm.half * 3;
quads.push([-E, -E, E, -H], [-E, H, E, E], [-E, -H, -H, H], [H, -E, E, H]);
console.log('quads ms', (performance.now() - t1).toFixed(1), 'count', quads.length);

// ---- 3/4. procedural textures ---------------------------------------------------------------
const t2 = performance.now();
const noise = makeNoiseTexture(256, 1337);
const wnormal = makeWaterNormalTexture(256, 3);
console.log('textures ms', (performance.now() - t2).toFixed(1));

// ---- probe lists -----------------------------------------------------------------------------
// shore: probed indices (row, col) chosen to hit sea, river, beach, downtown, mountains
const shoreProbes = [], shoreCells = [];
for (const [r, c] of [[0, 0], [129, 300], [257, 257], [300, 129], [400, 500], [500, 400],
  [129, 129], [300, 300], [456, 123], [88, 512], [512, 512], [356, 256], [420, 420], [45, 456], [500, 128]]) {
  shoreProbes.push(shore[r * N + c]);
  shoreCells.push([r, c]);
}
const shoreUnder = [...shore].filter((v) => v < 128).length;

// noise texels: 16 spread samples
const noiseProbes = [], wnormalProbes = [];
const texData = (t) => t.image.data;
const noiseArr = texData(noise), wnormalArr = texData(wnormal);
const texIdx = [];
for (let i = 0; i < 16; i++) {
  const t = i * 4093 + 7; // spread over 65536
  texIdx.push((t % 65536) * 4);
}
for (const k of texIdx) {
  noiseProbes.push([noiseArr[k], noiseArr[k + 1], noiseArr[k + 2], noiseArr[k + 3]]);
  wnormalProbes.push([wnormalArr[k], wnormalArr[k + 1], wnormalArr[k + 2], wnormalArr[k + 3]]);
}
const byteSum = (a) => { let s = 0; for (const v of a) s += v; return s; };
console.log("noise byteSum", byteSum(noiseArr), "wnormal byteSum", byteSum(wnormalArr));

// half-float patterns for a range of terrain heights
const halfProbes = [];
for (const h of [-24.5, -8.25, -0.5, -0.05, 0, 0.05, 1.5, 6.75, 24, 96.125, 172, 320.5, 512, 700.75]) {
  halfProbes.push(DataUtils.toHalfFloat(h));
}

// quad probes (first 12 + total count)
const quadProbes = quads.slice(0, 12).flat().map((v) => { const s = v.toFixed(1); return s; });

const goldens = {
  shoreProbes, shoreCells, shoreUnder, noiseProbes, wnormalProbes,
  noiseByteSum: byteSum(noiseArr), wnormalByteSum: byteSum(wnormalArr),
  halfProbes, quadProbes, quadCount: quads.length,
};

const kotlin = `// GENERATED by tools/probe_water.mjs — golden values from the REAL web water stack
// (Heightmap.js computeShoreDistance + textures.js makeNoiseTexture / makeWaterNormalTexture
// + Water.js _buildGeometry quad scan + THREE.DataUtils.toHalfFloat, size 2048 spacing 4 seed
// 1337 — the native grid). Do not edit by hand.
package com.fablecities.android.worldgen

object WaterGoldens {
    val shoreProbes = listOf(${shoreProbes.join(', ')})
    val shoreCells = listOf(${shoreCells.map((c) => 'listOf(' + c.join(', ') + ')').join(', ')})
    const val shoreUnder = ${shoreUnder}
    val noiseProbes = listOf(
${noiseProbes.map((p) => `        listOf(${p.join(', ')})`).join(',\n')},
    )
    val wnormalProbes = listOf(
${wnormalProbes.map((p) => `        listOf(${p.join(', ')})`).join(',\n')},
    )
    const val noiseByteSum = ${goldens.noiseByteSum}
    const val wnormalByteSum = ${goldens.wnormalByteSum}
    val halfProbes = listOf(${halfProbes.join(', ')})
    val quadProbes = listOf(${quadProbes.join(", ")})
    const val quadCount = ${quads.length}
}
`;
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/WaterGoldens.kt', import.meta.url), kotlin);
console.log('WaterGoldens.kt written');
console.log(JSON.stringify({ ...goldens, noiseProbes: '…', wnormalProbes: '…', quadProbes: '…' }, null, 1));
