// GroundControl golden probe — runs the REAL web ground rules in Node and emits
// android/app/src/test/java/com/fablecities/android/worldgen/GroundControlGoldens.kt
//
// Covers terrain/GroundControl.js makeGroundControl on the native heightmap grid
// (size 2048, spacing 4, seed 1337): the full 512x512 control bake exactly as
// terrain/index.js does it (controlAt + getSlope + shoreAt + curvatureAt), plus
// standalone forestMask probes. The native control map must show the SAME dry /
// dirt / sand / rock / canopy / field / curvature fields as the browser.
import { writeFileSync } from 'node:fs';
import { Heightmap } from '../src/modules/terrain/Heightmap.js';
import { makeGroundControl } from '../src/modules/terrain/GroundControl.js';

const hm = new Heightmap({ size: 2048, spacing: 4, seed: 1337 }).generate();
const ground = makeGroundControl(hm, 1337);
const { controlAt, forestMask } = ground;

// --- shore distance (same helper terrain/index.js bakes) ---------------------------------------
const shoreData = hm.computeShoreDistance();
const half = hm.half, spacing = hm.spacing, N = hm.N;
const clampN = (v, a, b) => (v < a ? a : v > b ? b : v);
const shoreAt = (x, z) => {
  const i = clampN(Math.round((x + half) / spacing), 0, N - 1);
  const j = clampN(Math.round((z + half) / spacing), 0, N - 1);
  return (shoreData[j * N + i] - 128) * 0.25;
};
const curvatureAt = (x, z, h) => {
  const e = 8;
  const lap = (hm.getHeight(x + e, z) + hm.getHeight(x - e, z) + hm.getHeight(x, z + e) + hm.getHeight(x, z - e) - 4 * h) / (e * e);
  return clampN(0.5 - lap * 45, 0.05, 0.95);
};

// --- the full control bake (terrain/index.js CONTROL_RES = 512) --------------------------------
const CONTROL_RES = 512;
const ctrlStep = hm.size / CONTROL_RES;
const ctrlData = new Uint8Array(CONTROL_RES * CONTROL_RES * 4);
const ctrl2Data = new Uint8Array(CONTROL_RES * CONTROL_RES * 4);
const t0 = performance.now();
for (let j = 0; j < CONTROL_RES; j++) {
  const z = -half + (j + 0.5) * ctrlStep;
  for (let i = 0; i < CONTROL_RES; i++) {
    const x = -half + (i + 0.5) * ctrlStep;
    const k = (j * CONTROL_RES + i) * 4;
    const h = hm.getHeight(x, z);
    const slope = hm.getSlope(x, z);
    const c = controlAt(x, z, h, slope, shoreAt(x, z));
    ctrlData[k] = 255 * c.dry; ctrlData[k + 1] = 255 * c.dirt; ctrlData[k + 2] = 255 * c.sand; ctrlData[k + 3] = 255 * c.rock;
    ctrl2Data[k] = 255 * c.forest; ctrl2Data[k + 1] = 255 * Math.min(Math.max(c.field, 0), 1); ctrl2Data[k + 2] = 0; ctrl2Data[k + 3] = 255 * curvatureAt(x, z, h);
  }
}
console.log('bake ms', (performance.now() - t0).toFixed(0));

// --- channel sums over the whole map (catches any rare divergence) ------------------------------
const chSum = (a, ch) => { let s = 0; for (let i = ch; i < a.length; i += 4) s += a[i]; return s; };
const ctrlSums = [0, 1, 2, 3].map((c) => chSum(ctrlData, c));
const ctrl2Sums = [0, 1, 2, 3].map((c) => chSum(ctrl2Data, c));

// --- probe rows: 8 rows x every-8th column x 8 channels ----------------------------------------
const probeRows = [0, 47, 128, 255, 296, 384, 441, 511];
const rowBytes = [];
for (const j of probeRows) {
  for (let i = 0; i < CONTROL_RES; i += 8) {
    const k = (j * CONTROL_RES + i) * 4;
    rowBytes.push(ctrlData[k], ctrlData[k + 1], ctrlData[k + 2], ctrlData[k + 3],
      ctrl2Data[k], ctrl2Data[k + 1], ctrl2Data[k + 2], ctrl2Data[k + 3]);
  }
}

// --- full-precision double probes (exact value checks, not just rounded bytes) ------------------
const pts = [];
for (let i = 0; i < 16; i++) {
  const x = -980 + i * 130 + (i % 3) * 7;   // pure arithmetic — identical doubles in the JVM
  const z = -860 + ((i * 197) % 1720);
  pts.push([x, z]);
}
const ctrlDoubles = [];
for (const [x, z] of pts) {
  const h = hm.getHeight(x, z);
  const slope = hm.getSlope(x, z);
  const c = controlAt(x, z, h, slope, shoreAt(x, z));
  ctrlDoubles.push([c.dry, c.dirt, c.sand, c.rock, c.forest, c.field, c.fieldEdge, curvatureAt(x, z, h)]);
}
const fmDoubles = [];
for (const [x, z] of pts) {
  const h = hm.getHeight(x, z);
  const slope = hm.getSlope(x, z);
  fmDoubles.push([forestMask(x, z, h, slope)]);
}
const curvDoubles = [];
for (const [x, z] of pts) {
  curvDoubles.push([curvatureAt(x, z, hm.getHeight(x, z))]);
}

const goldens = {
  ctrlSums, ctrl2Sums, rowBytes, probeRows,
  ctrlDoubles, fmDoubles, curvDoubles,
};

// JS doubles → shortest round-trip strings; Kotlin parses them back to identical bits.
const ds = (v) => {
  if (v === 0) return '0.0';
  if (Number.isInteger(v) && Math.abs(v) < 1e15) return v.toFixed(1);
  return String(v);
};
const kotlin = `// GENERATED by tools/probe_groundcontrol.mjs — golden values from the REAL web ground rules
// (terrain/GroundControl.js makeGroundControl on the native grid: size 2048, spacing 4,
// seed 1337 — full 512x512 control bake, terrain/index.js rules). Do not edit by hand.
package com.fablecities.android.worldgen

object GroundControlGoldens {
    val ctrlSums = listOf(${ctrlSums.join(', ')})
    val ctrl2Sums = listOf(${ctrl2Sums.join(', ')})
    val probeRows = listOf(${probeRows.join(', ')})
    /** 8 probe rows x 64 columns (every 8th) x 8 channels (ctrl RGBA, ctrl2 RGBA). */
    val rowBytes = listOf(
${[0, 1, 2].map(() => '').slice(0, 0).join('')}${chunk(rowBytes, 12).map((c) => '        ' + c.join(', ') + ',').join('\n')}
    )
    /** [x, z] probe points (pure arithmetic — identical doubles in the JVM). */
    val probePts = listOf(
${pts.map((p) => '        listOf(' + p.map(ds).join(', ') + ')').join(',\n')},
    )
    /** controlAt → [dry, dirt, sand, rock, forest, field, fieldEdge, curvature] at probePts. */
    val ctrlDoubles = listOf(
${ctrlDoubles.map((r) => '        listOf(' + r.map(ds).join(', ') + ')').join(',\n')},
    )
    /** forestMask (no pre) at probePts. */
    val fmDoubles = listOf(
${fmDoubles.map((r) => '        listOf(' + r.map(ds).join(', ') + ')').join(',\n')},
    )
    /** curvatureAt at probePts. */
    val curvDoubles = listOf(
${curvDoubles.map((r) => '        listOf(' + r.map(ds).join(', ') + ')').join(',\n')},
    )
}
`;
function chunk(a, n) {
  const out = [];
  for (let i = 0; i < a.length; i += n) out.push(a.slice(i, i + n));
  return out;
}
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/GroundControlGoldens.kt', import.meta.url), kotlin);
console.log('GroundControlGoldens.kt written');
console.log(JSON.stringify({ ...goldens, rowBytes: '…', ctrlDoubles: '…' }, null, 1));
