// Cloud golden probe — runs the REAL web cloud texture generators
// (proceduralNoise.js + Clouds.js + CloudShadow.js) in Node on seed 1337 and emits
// android/app/src/test/java/com/fablecities/android/worldgen/CloudGoldens.kt.
// The Kotlin port (worldgen/Clouds.kt) must reproduce the baked textures.
import { writeFileSync } from 'node:fs';
import { buildCloudNoiseTexture, buildWeatherTexture, buildCirrusTexture } from '../src/modules/environment/Clouds.js';
import { CloudShadowMap } from '../src/modules/environment/CloudShadow.js';

const SEED = 1337;
const t0 = performance.now();
const noise = buildCloudNoiseTexture(SEED).image.data;
const weather = buildWeatherTexture(SEED).image.data;
const cirrus = buildCirrusTexture(SEED).image.data;
console.log('cloud texture bake ms', (performance.now() - t0).toFixed(1));

const byteSum = (a) => { let s = 0; for (const v of a) s += v; return s; };

// spread texel probes (byte values; the Kotlin test allows ±1 for rounding-boundary cases)
const probes = (arr, count, stride) => {
  const out = [];
  for (let k = 0; k < count; k++) {
    const i = ((k * stride) % (arr.length / 4)) * 4;
    out.push([i, arr[i], arr[i + 1], arr[i + 2], arr[i + 3]]);
  }
  return out;
};
const noiseProbes = probes(noise, 24, 4093 + 1);
const weatherProbes = probes(weather, 20, 613 + 1);
const cirrusProbes = probes(cirrus, 20, 1021 + 1);

// shadow bake: coverage 0.3 (clear) and 0.96 (rain), strength 1
const shadow = new CloudShadowMap(buildWeatherTexture(SEED), buildCloudNoiseTexture(SEED), 22000);
shadow.update(0.30, 1.0);
const shadowClearSum = byteSum(shadow.data);
const shadowClearFrac = shadow.shadowFraction;
const shadowClearProbes = [];
for (let k = 0; k < 16; k++) {
  const i = (k * 4099 + 11) % shadow.data.length;
  shadowClearProbes.push([i, shadow.data[i]]);
}
shadow.update(0.96, 1.0);
const shadowRainSum = byteSum(shadow.data);
const shadowRainFrac = shadow.shadowFraction;

const K = [];
K.push('package com.fablecities.android.worldgen');
K.push('');
K.push('/** GENERATED by tools/probe_clouds.mjs from the REAL web cloud generators (seed 1337).');
K.push(' *  Byte probes allow ±1 LSB (double rounding boundaries); sums allow ±probes*1. */');
K.push('object CloudGoldens {');
K.push('    val noiseProbes = arrayOf(' + noiseProbes.map((p) => 'intArrayOf(' + p.join(', ') + ')').join(', ') + ')')
K.push('    val weatherProbes = arrayOf(' + weatherProbes.map((p) => 'intArrayOf(' + p.join(', ') + ')').join(', ') + ')')
K.push('    val cirrusProbes = arrayOf(' + cirrusProbes.map((p) => 'intArrayOf(' + p.join(', ') + ')').join(', ') + ')')
K.push('    val shadowClearProbes = arrayOf(' + shadowClearProbes.map((p) => 'intArrayOf(' + p.join(', ') + ')').join(', ') + ')')
K.push(`    const val noiseTexSum = ${byteSum(noise)}L`);
K.push(`    const val weatherTexSum = ${byteSum(weather)}L`);
K.push(`    const val cirrusTexSum = ${byteSum(cirrus)}L`);
K.push(`    const val shadowClearSum = ${shadowClearSum}L`);
K.push(`    const val shadowClearFrac = ${shadowClearFrac}`);
K.push(`    const val shadowRainSum = ${shadowRainSum}L`);
K.push(`    const val shadowRainFrac = ${shadowRainFrac}`);
K.push('}');
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/CloudGoldens.kt', import.meta.url), K.join('\n') + '\n');
console.log('CloudGoldens.kt written; sums:', byteSum(noise), byteSum(weather), byteSum(cirrus), shadowClearSum, shadowRainSum);
