// PuddleField golden probe — runs the REAL web puddle builder in Node and emits
// android/app/src/test/java/com/fablecities/android/worldgen/PuddleGoldens.kt
//
// Covers effects/PuddleField.js build() on a deterministic synthetic road network:
// gutter/rut pool placement (FNV id + seed 1337 mulberry32 stream), the drainage
// map raster (R pool / G tyre band / B corridor), pool lift + camber slope, and the
// merged feathered-disc geometry (positions / per-vertex alpha / indices).
import { writeFileSync } from 'node:fs';
import { PuddleField } from '../src/modules/effects/PuddleField.js';
import { ROAD_TYPES } from '../src/modules/roads/RoadTypes.js';

const seed = 1337;

// --- deterministic synthetic network: local + avenue + highway + path + unknown type -----------
const segs = new Map();
const add = (id, type, pts) => segs.set(id, { id, type, width: ROAD_TYPES[type] ? ROAD_TYPES[type].width : 10, points: pts });
{ // local street along x with a kink, 10 m steps
  const p = [];
  for (let i = 0; i <= 61; i++) p.push({ x: -300 + i * 10, z: -40 + (i > 30 ? 8 : 0) });
  add('seg-local-1', 'local', p);
}
{ // avenue with a linear drift
  const p = [];
  for (let i = 0; i <= 40; i++) { const z = -200 + i * 10; p.push({ x: 60 + 0.005 * (z + 200), z }); }
  add('seg-avenue-1', 'avenue', p);
}
{ // diagonal highway
  const p = [];
  for (let i = 0; i <= 40; i++) p.push({ x: -500 + i * 25, z: -500 + i * 18 });
  add('seg-highway-1', 'highway', p);
}
{ // footpath (cwHalf 1.2 < 1.6 → skipped for pools, still bounds the map)
  const p = [];
  for (let i = 0; i <= 10; i++) p.push({ x: 20 + i * 4, z: 120 + i * 2 });
  add('seg-path-1', 'path', p);
}
{ // unknown type → the width*0.34 fallback definition
  const p = [];
  for (let i = 0; i <= 20; i++) p.push({ x: -80 + i * 8, z: -120 + 0.25 * i });
  add('seg-odd-1', 'footway', p);
}

const world = {
  terrain: { getHeight: (x, z) => 3 + 0.004 * x - 0.002 * z },
  roads: {
    segments: segs,
    api: {
      types: Object.fromEntries(Object.entries(ROAD_TYPES).map(([k, t]) => [k, { definition: t }])),
      surfaceHeight: (x, z) => {
        if (x > 250) throw new Error('off-mesh'); // exercises the try/catch terrain fallback
        return 5.5 + 0.002 * x + 0.003 * z;
      },
    },
  },
};
const engine = { registerMaterial() {}, registerObject() {}, LAYER_NO_AO: 1 };
const scene = { add() {} };

const field = new PuddleField({ engine, scene, world, seed });
const count = field.build();
console.log('build →', count, 'pools; map', field.map.image.width, 'xf', field.mapXf.toArray().map((v) => +v.toFixed(4)));

// --- map goldens -------------------------------------------------------------------------------
const data = field.map.image.data;
const chSum = (ch) => { let s = 0; for (let i = ch; i < data.length; i += 4) s += data[i]; return s; };
let weighted = 0;
for (let i = 0; i < data.length; i++) weighted += (i % 251 + 1) * data[i];

// --- geometry goldens --------------------------------------------------------------------------
const pos = field.mesh.geometry.attributes.position.array;
const col = field.mesh.geometry.attributes.color.array;
const idx = field.mesh.geometry.index.array;
let posSum = 0; for (let i = 0; i < pos.length; i++) posSum += pos[i];
let colSum = 0; for (let i = 0; i < col.length; i++) colSum += col[i];
let idxSum = 0; for (let i = 0; i < idx.length; i++) idxSum = (idxSum + idx[i]) % 4294967296;

const f = (v) => { let s = String(v); if (s === '-0') s = '0.0'; if (!s.includes('.') && !s.includes('e') && !s.includes('Infinity')) s += '.0'; return s; };  // JS shortest round-trip repr — Kotlin parses back to identical bits
const discFloats = [];
for (let i = 0; i < 34 * 4 && i < pos.length; i++) discFloats.push(f(pos[i]));
const discAlphas = [];
for (let i = 0; i < 34 * 4 && i < col.length; i++) discAlphas.push(f(col[i]));
// per-disc centres (every 17th vertex): x, y (asphalt + LIFT), z
const centres = [];
for (let d = 0; d * 17 * 3 + 2 < pos.length && d < 14; d++) {
  centres.push([f(pos[d * 17 * 3]), f(pos[d * 17 * 3 + 1]), f(pos[d * 17 * 3 + 2])]);
}

const goldens = {
  poolCount: count,
  builtCount: field.count,
  lastBuildSegs: field.lastBuildSegs,
  mapSize: data.width ?? field.map.image.width,
  xf: [field.mapXf.x, field.mapXf.y, field.mapXf.z, field.mapXf.w],
  mapR: chSum(0), mapG: chSum(1), mapB: chSum(2), mapA: chSum(3),
  mapWeighted: weighted,
  posLen: pos.length, colLen: col.length, idxLen: idx.length,
  posSum, colSum, idxSum,
  discFloats, discAlphas, centres,
};

const kotlin = `// GENERATED by tools/probe_puddles.mjs — golden values from the REAL web PuddleField.js
// (deterministic synthetic network: local + avenue + highway + path + unknown-type segment,
// seed 1337, surfaceHeight + terrain fallback). Do not edit by hand.
package com.fablecities.android.worldgen

object PuddleGoldens {
    const val poolCount = ${count}
    const val builtCount = ${field.count}
    const val lastBuildSegs = ${field.lastBuildSegs}
    const val mapSize = ${field.map.image.width}
    val xf = listOf(${field.mapXf.toArray().map((v) => f(v)).join(', ')})
    const val mapR = ${chSum(0)}
    const val mapG = ${chSum(1)}
    const val mapB = ${chSum(2)}
    const val mapA = ${chSum(3)}
    const val mapWeighted = ${String(weighted)}
    const val posLen = ${pos.length}
    const val colLen = ${col.length}
    const val idxLen = ${idx.length}
    const val posSum = ${String(posSum)}
    const val colSum = ${f(colSum)}
    const val idxSum = ${idxSum}
    /** first 34 vertices x 4 (pos.xyz + colour.a), web Float32Array values */
    val discFloats = listOf(
${chunk(discFloats, 6).map((c) => '        ' + c.join(', ') + ',').join('\n')}
    )
    val discAlphas = listOf(
${chunk(discAlphas, 6).map((c) => '        ' + c.join(', ') + ',').join('\n')}
    )
    /** per-disc centres (x, y, z) for the first 14 pools */
    val centres = listOf(
${centres.map((c) => '        listOf(' + c.join(', ') + ')').join(',\n')},
    )
}
`;
function chunk(a, n) {
  const out = [];
  for (let i = 0; i < a.length; i += n) out.push(a.slice(i, i + n));
  return out;
}
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/PuddleGoldens.kt', import.meta.url), kotlin);
console.log('PuddleGoldens.kt written');
console.log(JSON.stringify({ ...goldens, discFloats: '…', discAlphas: '…' }, null, 1));
