// Traffic golden probe — runs the REAL web traffic/TrafficSim.js in Node on a minimal fake
// net (a single closed-loop lane, no junctions) and emits worldgen/TrafficGoldens.kt.
// The Kotlin port (worldgen/Traffic.kt) must reproduce spawn + IDM integration bit-exactly.
import { writeFileSync } from 'node:fs';
import { TrafficSim } from '../src/modules/traffic/TrafficSim.js';
import { VEHICLE_IDS, VEHICLE_SPECS } from '../src/modules/traffic/VehicleModels.js';
import { makeRng, hashString } from '../src/shared/random.js';

// --- a deterministic closed-loop lane: 16 points, radius 300 m, gentle height variation ---
const PTS = [];
for (let i = 0; i < 16; i++) {
  const a = (i / 16) * Math.PI * 2;
  PTS.push([Math.cos(a) * 300.0, 2.0 + Math.sin(a * 3.0) * 1.5, Math.sin(a) * 300.0]);
}
// makePoly (copied from LaneNetwork.js — module-private there)
const KMH = 1 / 3.6, LAT_ACC = 3.4;
function makePoly(pts, speed) {
  const n = pts.length;
  const x = new Float32Array(n), y = new Float32Array(n), z = new Float32Array(n);
  const cum = new Float32Array(n);
  for (let i = 0; i < n; i++) { x[i] = pts[i][0]; y[i] = pts[i][1]; z[i] = pts[i][2]; }
  for (let i = 1; i < n; i++) cum[i] = cum[i - 1] + Math.hypot(x[i] - x[i - 1], z[i] - z[i - 1], y[i] - y[i - 1]);
  const vmax = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    let v = speed;
    if (i > 0 && i < n - 1) {
      const ax = x[i] - x[i - 1], az = z[i] - z[i - 1];
      const bx = x[i + 1] - x[i], bz = z[i + 1] - z[i];
      const la = Math.hypot(ax, az), lb = Math.hypot(bx, bz);
      if (la > 1e-3 && lb > 1e-3) {
        const cross = Math.abs(ax * bz - az * bx);
        const cx = x[i + 1] - x[i - 1], cz = z[i + 1] - z[i - 1];
        const lc = Math.hypot(cx, cz) || 1;
        const kappa = (2 * cross) / (la * lb * lc);
        if (kappa > 1e-4) v = Math.min(v, Math.sqrt(LAT_ACC / kappa));
      }
    }
    vmax[i] = Math.max(2.6, v);
  }
  for (let i = n - 2; i >= 0; i--) vmax[i] = Math.min(vmax[i], Math.sqrt(vmax[i + 1] * vmax[i + 1] + 2 * 1.6 * (cum[i + 1] - cum[i])));
  return { n, x, y, z, cum, vmax, len: cum[n - 1] };
}
const poly = makePoly(PTS, 50 * KMH);
console.log('poly len', poly.len.toFixed(3), 'vmax[0..3]', poly.vmax.slice(0, 4).map((v) => v.toFixed(3)).join(','));

// --- fake net: one loop lane, no junctions, randomLane = lane 0 (no rng consumption) ---
const lane = { idx: 0, kind: 0, poly, speed: 50 * KMH, rank: 2, outs: [0] };
const net = {
  ready: true,
  elements: [lane],
  nodes: new Map(),
  randomLane: () => 0,
  route: () => null,
  updateSignals: () => {},
  pedElements: [],
};

const SEED = 1337;
const rng = makeRng(SEED).fork(hashString('traffic'));
console.log('traffic rng seed', hashString('traffic') >>> 0);
const sim = new TrafficSim(net, { seed: SEED }, rng);
sim.onNetwork();

// idmAccel probes
const A_MAX = 2.85, B_COMF = 3.30, S0 = 2.05, T_HEAD = 1.05;
function idmAccel(v, v0, gap, dv, aMax) {
  const free = 1 - Math.pow(Math.max(0, v) / Math.max(0.5, v0), 4);
  let inter = 0;
  if (gap < 1e8) {
    const sStar = S0 + Math.max(0, v * T_HEAD + (v * dv) / (2 * Math.sqrt(aMax * B_COMF)));
    const g = Math.max(0.4, gap);
    inter = (sStar / g) * (sStar / g);
  }
  return aMax * (free - inter);
}
const idmProbes = [];
for (const [v, v0, gap, dv] of [[10, 13, 1e9, 0], [8, 13, 12, -2], [5, 13, 4.5, 3], [13, 13, 30, 0], [2, 13, 1.2, 1], [0, 10, 1e9, 0]]) {
  idmProbes.push(idmAccel(v, v0, gap, dv, A_MAX));
}

// spawn 8 vehicles, then 200 steps of 0.05 s
const made = sim.spawn(40);
console.log('spawned', made);
for (let i = 0; i < 400; i++) sim.update(0.05);

const veh = sim.vehicles.map((v) => ({
  t: v.type,
  s: v.s.toFixed(9), v: v.v.toFixed(9), x: v.x.toFixed(9), z: v.z.toFixed(9),
  yaw: v.yaw.toFixed(9), br: v.brake.toFixed(9), ri: v.ri, route: v.route.length,
}));
console.log('vehicles after 400 steps:', veh.length, 'avgSpeedRatio', sim.avgSpeedRatio.toFixed(6));

const goldens = {
  polyLen: +poly.len.toFixed(9),
  vmaxProbes: [poly.vmax[0], poly.vmax[4], poly.vmax[8], poly.vmax[12]].map((v) => +v.toFixed(9)),
  idmProbes: idmProbes.map((v) => +v.toFixed(9)),
  spawned: made,
  trafficSeed: hashString('traffic') >>> 0,
  count: sim.vehicles.length,
  veh,
};

const kotlin = `// GENERATED by tools/probe_traffic.mjs — golden values from the REAL web traffic/TrafficSim.js
// (seed 1337, rng fork hashString('traffic'), one closed-loop lane, 8 spawns, 200 x 0.05 s steps).
// Do not edit by hand.
package com.fablecities.android.worldgen

object TrafficGoldens {
    class VehG(val typeId: String, val s: Double, val v: Double, val x: Double, val z: Double,
               val yaw: Double, val brake: Double, val ri: Int, val route: Int)

    const val polyLen = ${goldens.polyLen}
    val vmaxProbes = listOf(${goldens.vmaxProbes.join(', ')})
    val idmProbes = listOf(${goldens.idmProbes.join(', ')})
    const val spawned = ${made}
    const val trafficSeed = ${goldens.trafficSeed}L
    const val count = ${goldens.count}
    val veh = listOf(
${veh.map((v) => `        VehG("${v.t}", ${v.s}, ${v.v}, ${v.x}, ${v.z}, ${v.yaw}, ${v.br}, ${v.ri}, ${v.route})`).join(',\n')},
    )
}
`;
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/TrafficGoldens.kt', import.meta.url), kotlin);
console.log('TrafficGoldens.kt written');
