// WetLights golden probe — drives the REAL web WetLights.js update() in Node and emits
// android/app/src/test/java/com/fablecities/android/worldgen/WetLightsGoldens.kt
//
// The ranking half of WetLights.js is pure CPU: the camera frame, the mirrored-plane loci,
// the cosA x prominence sort and the red-tail slot reservation never touch GL. The probe feeds
// a synthetic camera + a synthetic lamp set + a synthetic glare list (the same shape the native
// renderer authors) and pins the published 12-slot array.
import { writeFileSync } from 'node:fs';
import { WetLights } from '../src/modules/effects/WetLights.js';

// synthetic scene: an InstancedMesh-shaped stub is traversed by WetLights._harvestLamps, which
// reads o.isInstancedMesh / o.name / o.visible / o.count / o.getMatrixAt / geometry.groups —
// build the lamp bulbs directly instead by stubbing the harvest input through update()'s scene.
// Simplest faithful path: call update() with a scene stub exposing the lamps mesh.
function lampMesh(name, mats) {
  const n = mats.length;
  return {
    isInstancedMesh: true,
    name,
    visible: true,
    count: n,
    geometry: {
      groups: [{ materialIndex: 1, start: 0, count: 3 }],
      attributes: { position: { getX: () => 0, getY: () => 0, getZ: () => 0, count: 3 } },
    },
    getMatrixAt(i, m) {
      // translation-only matrix (bulb at the recorded position)
      m.elements[12] = mats[i][0]; m.elements[13] = mats[i][1]; m.elements[14] = mats[i][2];
    },
  };
}
function glareMesh(records) {
  return {
    isInstancedMesh: true,
    name: 'traffic-lamp-glare',
    visible: true,
    count: records.length,
    parent: {},
    geometry: { getAttribute: (n) => (n === 'aGlare' ? { array: records.flatMap((r) => [r[3], r[4], r[5]]) } : null) },
    getMatrixAt(i, m) {
      m.elements[12] = records[i][0]; m.elements[13] = records[i][1]; m.elements[14] = records[i][2];
    },
  };
}
const camStub = {
  position: { x: 0, y: 22, z: 0 },
  matrixWorld: {
    // column 2 = camera +Z = (0, 0.447, 0.894) → forward = negate = (0, -0.447, -0.894), 26.6° down
    elements: [1, 0, 0, 0, 0, 0.894, -0.447, 0, 0, 0.447, 0.894, 0, 0, 0, 0, 1],
    setFromMatrixColumn(i, v) {
      v.set(this.elements[i * 4], this.elements[i * 4 + 1], this.elements[i * 4 + 2]);
      return v;
    },
  },
  getWorldPosition(v) { v.set(0, 22, 0); return v; },
};
// camera forward -Z (matrix column 2 negated in WetLights: _fwd.setFromMatrixColumn(2).negate())
// our matrix has column 2 = (0,0,1) → forward = (0,0,-1)
const sceneStub = {
  lamps: lampMesh('roads/lamps', [
    [-2, 9, -24], [30, 9, -40], [-30, 9, -44], [60, 9, -26], [0, 9, -2600], // last: out of range
  ]),
  glare: glareMesh([
    // tails behind the camera-to-be (red dominant): x, y, z, r, g, b
    [2, 0.66, -26, 1.00, 0.075, 0.030],
    [16, 0.66, -28, 0.60, 0.045, 0.018],
    // a headlamp pair ahead
    [4, 0.62, -44, 1.32, 1.18, 0.94],
    [-4, 0.62, -46, 1.32, 1.18, 0.94],
    // a dim one that must be rejected by the 0.02 floor
    [10, 0.66, -30, 0.01, 0.01, 0.01],
  ]),
};
sceneStub.traverse = (fn) => { fn(sceneStub.lamps); fn(sceneStub.glare); };

const wl = new WetLights();
wl.update(0.016, sceneStub, camStub, 1, 1.0, 0.0);
console.log('published', wl.count, 'stats', JSON.stringify(wl.stats));

const ds = (v) => {
  let s = String(v);
  if (s === '-0') s = '0.0';
  if (!s.includes('.') && !s.includes('e') && !s.includes('Infinity')) s += '.0';
  return s;
};
const rows = [];
for (let i = 0; i < 12; i++) {
  rows.push([wl.pos[i].x, wl.pos[i].y, wl.pos[i].z, wl.pos[i].w,
    wl.col[i].r, wl.col[i].g, wl.col[i].b]);
}
let tails = 0;
for (let i = 0; i < wl.count; i++) if (wl.col[i].r > 2.5 * Math.max(wl.col[i].g, 0.02)) tails++;

const kotlin = `// GENERATED by tools/probe_wetlights.mjs — goldens from the REAL web WetLights.js update()
// (synthetic camera + lamp mesh + traffic-lamp-glare mesh, exposure 1.0, planeY 0)
package com.fablecities.android.worldgen

object WetLightsGoldens {
    const val published = ${wl.count}
    const val statsLamps = ${wl.stats.lamps}
    const val statsVehicles = ${wl.stats.vehicles}
    const val tailsInSlots = ${tails}
    /** 12 slots: x, y, z, intensity, r, g, b */
    val slots = listOf(
${rows.map((p) => '        listOf(' + p.map(ds).join(', ') + ')').join(',\n')},
    )
}
`;
writeFileSync(new URL('../android/app/src/test/java/com/fablecities/android/worldgen/WetLightsGoldens.kt', import.meta.url), kotlin);
console.log('WetLightsGoldens.kt written');
